Try to parse the year when 'year' tag could be a date
dhowden/tag pull request #104
Opened 2024-02-03 14:41 UTC by JorgeLNJunior

When the year/date tag is a date, it can't be parsed into a number, so the `Year()` method returns a zero value. This PR tries to fix this by checking if the `Atoi()` function returns 0. If it does, the string is parsed as a date, and the year is returned. If parsing fails, it still returns zero.

2024-04-13 02:53 UTC, dhowden requested changes
Thanks for the change!  Slight simplification to make it more clear that we're not changing behaviour when `year = 0` (nonsense though that would be!).

2024-04-13 02:53 UTC, dhowden commented on id3v2metadata.go
> +	}
```suggestion
	if year, err := strconv.Atoi(stringYear); err == nil {
		return year
	}
```

2024-04-13 22:42 UTC, dhowden approved these changes

2024-04-13 22:47 UTC, dhowden commented
So I completely missed that the build was failing on here!  `time.DateOnly` is go1.20+, will bump the version in `go.mod`.

2024-04-13 23:06 UTC, dhowden commented
...and I can't fix this it would seem.  Can you bump the go.mod to 1.20 as that's the requirement for this?

2024-04-14 14:45 UTC, JorgeLNJunior commented
Done.

2024-04-15 13:12 UTC, JorgeLNJunior commented
I forgot the workflow file, now it should pass.

2024-04-15 22:43 UTC, dhowden requested changes

2024-04-15 22:43 UTC, dhowden commented on .github/workflows/go.yml
> +        go-version: 1.20
I think you might need "1.20" here?

2024-04-17 05:33 UTC, dhowden approved these changes

2024-04-17 05:37 UTC, merged