Return artist instead of performer for vorbis tags
dhowden/tag pull request #97
Opened 2022-12-22 04:22 UTC by melvyn2

Also fix possibly a mistake where the empty performer tag would be returned for the composer mathod.

2022-12-23 04:32 UTC, itslychee commented
Thanks for the PR! I should have done this after filing an issue, such behavior shouldn't exist in tag.

2023-02-11 14:02 UTC, bertvandepoel commented
@dhowden have you considered this PR already? It seems quite sensible to me

2023-05-30 22:31 UTC, dhowden requested changes
So this is interesting.  I suspect I set this up to make the classical "more correct", but I don't actually have any files using this code so don't see why we shouldn't change it!

2023-05-30 22:31 UTC, dhowden commented on vorbis.go
> -	// ARTIST
Include the PERFORMER blurb here so that we can keep track.

2023-06-30 03:38 UTC, merged