add: fn{parse, acceptedFileTypes};
dhowden/tag pull request #99
Opened 2023-05-19 18:57 UTC by kendfss

2023-05-21 10:52 UTC, bertvandepoel commented
Would you consider maybe adding a clearer title and a little description of what this PR does and what its aim is. Commit messages in this project aim at explaining what the change does, not how the code has changed. This hardly gives an idea what feature you add or what problem you solve except if people go look at the code.

Thank you!

2023-05-23 03:55 UTC, kendfss commented
Sorry. The parse function takes a file path and produces a metadata for readonly use-case

the AcceptedFileTypes function allows users to iterate over accepted file types, say when creating a tree-walking file organizer, to avoid trying to check any files that may not match. Could use MIME types for that, but not sure the time tradeoff is worthwile for my use case.

Ultimately, just sharing them because I wanted to keep using them without continuing to use a fork, but if you don't want them that's fair too.

2023-05-25 07:15 UTC, bertvandepoel commented
Thanks for adding some more info. I'm actually not the developer of this library and not even that good at Go. I'm following this repo however since I'm quite invested in its maintenance and I hope someone will at some point contribute writing functionality to it! I expect that @dhowden will respond to your PR in due time :)

2023-05-25 07:36 UTC, wader commented
@bertvandepoel what kind of functionality are you looking for? can maybe help if not too big

2023-05-26 07:23 UTC, bertvandepoel commented
> @bertvandepoel what kind of functionality are you looking for? can maybe help if not too big

I'm afraid I'm hoping for #15 (aka #71). So not really a small thing to achieve I'm afraid. But let's discuss that inside those issues and not derail this PR :)

2023-05-30 22:25 UTC, dhowden requested changes
Hey!  Thanks for the change.

Understand completely the motivation to have the supported file types exported as a list.  Having `Parse` (not sure of the naming here - is there precedent?) as a convenience makes sense too.

2024-12-22 15:31 UTC, closed without merging